server:
  port:
    8070

client:
  eureka:
    register-with-eureka: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # services
        - id: tasks-service
          uri: http://localhost:8081
          predicates:
            - Path=/tasks/**
          filters:
            - StripPrefix=1
        - id: users-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
  config:
    import: optional:configserver:http://localhost:8888